version: "3.4"
name: progress-hub-v2
services:
  api:
    container_name: ProgressHubApi
    image: progresshubapi
    env_file:
      - .env
    build:
      context: .
      dockerfile: ProgressHubApi/Dockerfile
    ports:
      - 8000:80

  db:
    container_name: Mongo
    image: mongo
    volumes:
      - ./db-data/mongo/:/data/db
    ports:
      - 27017:27017

  web:
    container_name: ProgressHubWeb
    image: progresshubweb
    build:
      context: ProgressHubWeb
      target: builder
    ports:
      - 4200:4200
    volumes:
      - ./progresshubweb:/project
      - /project/node_modules
